### ISSUE TITLE
why is this trending? 

### ISSUE THREAD

**Issue by ghost** [antoniosarosi/Wallpapers#1]

**Comment by thebatclaudio** [comment]
Everyone wants a good wallpaper

**Comment by dinkopehar** [comment]
I assume it's because he published a [video](https://www.youtube.com/watch?v=N17zVGfrTiQ) about how he customised his dev environment. You can see section about wallpapers at the beginning of video.

**Comment by SurendraPrasadSH** [comment]
people like to change their wallpapers for a fresh looking desktop IG XD

**Comment by ghost** [comment]
yp they are actually nice , i had posted it without seeing whats inside , tho i still refer my blank dekstop to anything
